# Generated by Django 5.0 on 2023-12-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celular',
            old_name='sistema_operacionasl',
            new_name='sistema_operacional',
        ),
    ]
